repository: &repo "docker.io"

newapi:
  repo: *repo
  image: calciumion/new-api:latest
  replicaCount: 1
  port: 3000
  environment:
    SQL_DSN: "root:123456@tcp(newapi-mysql:3306)/newapi"
    REDIS_CONN_STRING: "redis://newapi-redis"
    TZ: "Asia/Shanghai"
  volumes:
    data:
      name: openapi-data
      storage: 1Gi
      storageClass: ceph-rbd 
  healthCheckPath: /api/status
redis:
  repo: *repo
  image: redis:latest

mysql:
  repo: *repo
  image: mysql:8.4.0-oraclelinux8
  volumes:
    data:
      name: openapi-mysql-data
      storage: 1Gi
      storageClass: ceph-rbd
  rootPassword: "123456"
  database: newapi
